name: CI/CD
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
          registry-url: https://registry.npmjs.org/
      - name: Publish New Version
        if: github.ref == 'refs/heads/master'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd simon-ui
          yarn
          yarn version --new-version patch --no-git-tag-version
          yarn publish
          cd ../web
          yarn add simon-ui --latest
          cd ..
          git config --local user.email "simonboisset.dev@gmail.com"
          git config --local user.name "simonboisset"
          git add .
          git commit -m "New version"
          git push
      - name: Checkout dev
        uses: actions/checkout@v2
        if: github.ref == 'refs/heads/master'
        with:
          ref: 'dev'
          fetch-depth: '0'
      - name: Rebase Dev
        if: github.ref == 'refs/heads/master'
        run: |
          git rebase remotes/origin/master
          git push
